In [1]:
import pandas as pd

In [21]:
df = pd.read_csv('Datasets/수도권 영화상영관정보_2021-10-14.csv', encoding='UTF-8')
df.head()

,광역단체,기초단체,영화상영관코드,영화상영관명,총 스크린수,총 좌석수,필름 상영관수,2D 상영관수,3D 상영관수,4D 상영관수,...,상설여부,특별관운영여부,가입여부,전송사업자명,개관일,영업상태,운영형태,주소,전화번호,홈페이지
0,서울시,노원구,1235,롯데시네마 노원수락산역,5,634,0,5,0,0,...,상설,NaN,가입,롯데컬처웍스(주)롯데시네마,2015-11-13,영업,위탁,서울특별시 노원구 상계동 1132-35 번지 3~9층,1544-8855,www.lottecinema.co.kr
1,서울시,강남구,1003,메가박스 코엑스,19,"3,434",0,19,3,0,...,상설,NaN,가입,메가박스(주),2000-05-13,영업,직영,서울특별시 강남구 삼성동 159 번지,1544-0070,http://www.megabox.co.kr/
2,서울시,강남구,1242,이봄씨어터,1,59,0,1,0,0,...,상설,NaN,가입,인터파크(주),2017-01-11,영업,직영,서울특별시 강남구 신사동 532-1 번지 대원빌딩 B2,070-8233-4321,NaN
3,서울시,서대문구,1148,아트하우스모모,2,276,2,2,1,0,...,상설,NaN,가입,(주)디트릭스,2008-08-01,영업,위탁,서울특별시 서대문구 대현동 11-1 번지 이화여자대학교 이화캠퍼스콤플렉스(지하4층),02-747-7782,http://www.arthousemomo.com/
4,서울시,성북구,1271,CGV 성신여대입구,5,768,0,5,0,0,...,상설,NaN,가입,CJ올리브네트웍스(주),2008-09-11,영업,직영,서울특별시 성북구 동선동1가 1-2 번지 유타몰 10~12층,NaN,http://www.cgv.co.kr

In [26]:
df = df[['광역단체', '기초단체', '영화상영관명', '전송사업자명', '주소']]
aa.head()

In [27]:
aa.head()

,광역단체,기초단체,영화상영관명,전송사업자명,주소
0,서울시,노원구,롯데시네마 노원수락산역,롯데컬처웍스(주)롯데시네마,서울특별시 노원구 상계동 1132-35 번지 3~9층
1,서울시,강남구,메가박스 코엑스,메가박스(주),서울특별시 강남구 삼성동 159 번지
2,서울시,강남구,이봄씨어터,인터파크(주),서울특별시 강남구 신사동 532-1 번지 대원빌딩 B2
3,서울시,서대문구,아트하우스모모,(주)디트릭스,서울특별시 서대문구 대현동 11-1 번지 이화여자대학교 이화캠퍼스콤플렉스(지하4층)
4,서울시,성북구,CGV 성신여대입구,CJ올리브네트웍스(주),서울특별시 성북구 동선동1가 1-2 번지 유타몰 10~12층

In [25]:
df.groupby('전송사업자명').count()

,광역단체,기초단체,영화상영관코드,영화상영관명,총 스크린수,총 좌석수,필름 상영관수,2D 상영관수,3D 상영관수,4D 상영관수,IMAX 상영관수,상설여부,특별관운영여부,가입여부,개관일,영업상태,운영형태,주소,전화번호,홈페이지
전송사업자명,,,,,,,,,,,,,,,,,,,,
(주)디트릭스,9,9,9,9,9,9,9,9,9,9,9,9,0,9,8,9,9,9,8,6
(주)씨네큐,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0
(주)활엔터테인먼트,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0
CJ올리브네트웍스(주),84,84,84,84,84,84,84,84,84,84,84,84,0,84,84,84,84,82,61,49
롯데컬처웍스(주)롯데시네마,71,71,71,71,71,71,71,71,71,71,71,71,0,71,71,71,71,71,64,59
메가박스(주),48,48,48,48,48,48,48,48,48,48,48,48,0,48,48,48,48,48,46,43
예스이십사 주식회사,10,10,10,10,10,10,10,10,10,10,10,10,0,10,8,10,10,10,10,8
인터파크(주),12,12,12,12,12,12,12,12,12,12,12,12,0,12,12,12,12,11,11,5